### ISSUE TITLE
Updates are failing

### ISSUE THREAD

**Issue by knd775** [huntabyte/static#1]
Looks like updates are failing due to a permissions issue https://github.com/huntabyte/static/actions/runs/8196651355/job/22417309742#step:7:64

(I'm not particularly bothered by not being included, just thought you might want to know since you went through the effort of setting this up)

**Comment by huntabyte** [comment]
Wow, thanks a ton for pointing this out! I kept seeing the action "succeed" but noticed the sponsored images weren't updating!

**Comment by huntabyte** [comment]
Fixed by giving github actions write permissions in the repo!
